Gestcom_coccinelle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('produits/', include('Produits.urls')),
    path('stock/', include('Stocks.urls')),
    path('vente/', include('Vente.urls')),
    path('tiers/', include('tiers.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from .views import CaissierChangePasswordView


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('caissier/changer-mot-de-passe/', CaissierChangePasswordView.as_view(), name='changer_mot_de_passe_caissier'),
    path('dashboard/admin/', views.dashboard_admin, name='dashboard_admin'),
    path('dashboard/caissier/', views.dashboard_caissier, name='dashboard_caissier'),
    path('utilisateurs/', views.gestion_caissiers, name='gestion_caissier'),
    path('utilisateurs/ajouter/', views.ajouter_caissier, name='ajouter_caissier'),
    path('utilisateurs/<int:pk>/modifier/', views.modifier_caissier, name='modifier_caissier'),
    path('api/ventes-semaine/', views.ventes_semaine, name='ventes_semaine'),
    path('mon_profil/', views.modifier_profil, name='profil_utilisateur'),


    path('modifier-infos/', views.modifier_infos, name='modifier_infos'),
    path('profil/', views.profil_utilisateur0, name='profil'),

    # urls.py
path('changer-photo/', views.changer_photo, name='changer_photo'),

    path('modifier-mot-de-passe/', views.modifier_mot_de_passe, name='modifier_mot_de_passe'),

# Exemple dans urls.py
path("alertes-stock/", views.stock_alertes, name="stock_alertes"),

    path('ventes-7-jours/', views.ventes_7_derniers_jours, name='ventes_7_derniers_jours'),


    path('api/revenus/', views.api_revenus, name='api_revenus'),

    path('api/stats/', views.stats_data, name='stats_data'),
path('details/<int:id_vente>/', views.details_vente_ajax, name='details_vente_ajax'),
path(' liste_ventes/', views.liste_ventes, name='liste_ventes'),
    path('facture/<str:code_facture>/', views.imprimer_facture, name='imprimer_facture'),


]

core/urls.py
from django.urls import path
from .views import home 


urlpatterns = [
    path('', home, name='home'),
    
]

accounts/models.py
from django.db import models

# Create your models here.

baseSQL/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from datetime import date
from django.utils import timezone
from datetime import timedelta


class Utilisateur(AbstractUser):

    ROLE_CHOICES= [
        ('admin', 'Administrateur'),
        ('caissier','Caissier'),
    ]
    last_activity = models.DateTimeField(null=True, blank=True)
    id_utilisateur = models.AutoField(primary_key=True)
    contact = models.CharField(max_length=250, unique=True)
    adresse = models.CharField(max_length=100)
    email =models.CharField(max_length=100, unique=True)
    role = models.CharField(max_length=8, choices=ROLE_CHOICES, default='caissier')
    statut = models.CharField(max_length=7)
    photo = models.ImageField(upload_to='accounts/', null=True, blank=True)
    ##fist_login= models.BooleanField(default=True)


    def __str__(self):
        return self.username
    @property
    def is_online(self):
        if self.last_activity:
            return timezone.now() - self.last_activity < timedelta(seconds=30)
        return False
    
    class Meta:
        managed = True
        db_table = 'utilisateur'

class ProfilCaissier(models.Model):
    utilisateur = models.OneToOneField('baseSQL.Utilisateur', on_delete=models.CASCADE)
    first_login= models.BooleanField(default=True)

    class Meta:
        managed = True
        db_table = 'profil_caissier'
class Approvisionnement(models.Model):
    id_appro = models.AutoField(primary_key=True)
    id_utilisateur = models.ForeignKey('baseSQL.Utilisateur', models.DO_NOTHING, db_column='id_utilisateur')
    id_frs = models.ForeignKey('Fournisseur', models.DO_NOTHING, db_column='id_frs')
    date = models.DateTimeField()
    montant_total = models.DecimalField(max_digits=10, decimal_places=2)
    date_expiration = models.DateField(null=True, blank=True)  

    def est_proche_expiration(self):
        if self.date_expiration:
            delta = (self.date_expiration - date.today()).days
            return 0 < delta <= 7
        return False

    def est_expire(self):
        if self.date_expiration:
            return self.date_expiration < date.today()
        return False

    class Meta:
        managed = True
        db_table = 'approvisionnement'


class MouvementStock(models.Model):
    TYPE_CHOICES = [
        ('entrée', 'Entrée'),
        ('sortie','Sortie'),
        ('retour', 'Retour'),
        ('ajustement', 'Ajustement'),
        ('aprovisionement','Approvisionement'),
        ('transfert','Transfert'),
    ]

    produit = models.ForeignKey('baseSQL.Produit', on_delete=models.CASCADE)
    type_mouvement = models.CharField(max_length=20, choices=TYPE_CHOICES)
    quantite = models.IntegerField()
    utilisateur  =  models.ForeignKey('baseSQL.Utilisateur', on_delete=models.SET_NULL, null=True)
    date_mouvement = models.DateTimeField(auto_now_add=True)
    commentaire= models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.type_mouvement} - {self.produit.nom} ({self.quantite})"
    class Meta:
        managed = True
        db_table = 'mouvement_stock'        

class Vente(models.Model):
    id_vente = models.AutoField(primary_key=True)
    id_client = models.ForeignKey('baseSQL.Client', models.DO_NOTHING, db_column='id_client')
    id_utilisateur = models.ForeignKey('baseSQL.Utilisateur', models.DO_NOTHING, db_column='id_utilisateur', related_name='ventes')
    date_vente = models.DateTimeField()
    montanttotal = models.DecimalField(db_column='montantTotal', max_digits=10, decimal_places=2)  # Field name made lowercase.
    remise = models.DecimalField(max_digits=5, decimal_places=2, default=0, verbose_name="Remise (%)")

    statut = models.CharField(max_length=10)

    class Meta:
        managed = True
        db_table = 'vente'


class Commande(models.Model):
    id_commande = models.AutoField(primary_key=True)
    id_client= models.ForeignKey('baseSQL.Client', models.DO_NOTHING, db_column='id_client')
    id_utilisateur = models.ForeignKey('baseSQL.Utilisateur', models.DO_NOTHING, db_column='id_utilisateur')
    id_frs= models.ForeignKey('baseSQL.Fournisseur', models.DO_NOTHING, db_column='id_frs')

    date_commande = models.DateTimeField()
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = True
        db_table = 'commande'        


class CategorieProduit(models.Model):
    id_categorie = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=100)
    description = models.TextField()
    def __str__(self):
        return self.nom
    class Meta:
        managed = True
        db_table = 'categorie_produit'

class Produit(models.Model):
    id_produit = models.AutoField(primary_key=True)
    categorie = models.ForeignKey('baseSQL.CategorieProduit', on_delete=models.CASCADE)
    nom_produit = models.CharField(max_length=100)
    codes_barres = models.CharField(max_length=100, unique=True, null=True, blank=True)
    reference = models.CharField(max_length=100)
    description = models.TextField()
    quantite = models.IntegerField()
    prix_achat = models.DecimalField(max_digits=10, decimal_places=2)
    prix_vente = models.DecimalField(max_digits=10, decimal_places=2)
    stock_actuel = models.IntegerField()
    stock_min = models.IntegerField()
    image = models.ImageField(upload_to='produits/', blank=True, null=True)
    def __str__(self):
        return f"{self.nom_produit} ({self.reference})"
    class Meta:
        managed = True
        db_table = 'produit'        



class Client(models.Model):
    id_client = models.AutoField(primary_key=True)
    nom_client = models.CharField(max_length=100)
    contact = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=255, unique=True,blank=True, null=True)
    adresse = models.CharField(max_length=255, blank=True, null=True)
    point = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.nom_client} - {self.contact}"
    
    class Meta:
        managed = True
        db_table = 'client'




class Facture(models.Model):
    id_facture = models.AutoField(primary_key=True)
    id_vente = models.ForeignKey('Vente', models.DO_NOTHING, db_column='id_vente')
    code_facture = models.CharField(max_length=100)
    date_emission = models.DateTimeField()
    date_paiement = models.DateTimeField()
    montant_ht = models.DecimalField(db_column='montant_HT', max_digits=10, decimal_places=2)  # Field name made lowercase.
    montant_ttc = models.DecimalField(db_column='montant_TTC', max_digits=10, decimal_places=2)  # Field name made lowercase.
    montant_net = models.DecimalField(max_digits=10, decimal_places=2)
    mode_paiement = models.CharField(max_length=11)

    class Meta:
        managed = True
        db_table = 'facture'


class Fournisseur(models.Model):
    id_frs = models.AutoField(primary_key=True)
    nom_frs = models.CharField(max_length=100)
    contact = models.CharField(max_length=100, unique=True)
    email = models.CharField(max_length=100, unique=True)
    adresse = models.CharField(max_length=100)
    pays = models.CharField(max_length=100)
    type_frs = models.CharField(max_length=11)

    def __str__(self):
        return f"{self.nom_frs}"
    class Meta:
        managed = True
        db_table = 'fournisseur'


class LigneAppro(models.Model):
    id_ligneappro = models.AutoField(db_column='id_ligneAppro', primary_key=True)  # Field name made lowercase.
    id_appro = models.ForeignKey('baseSQL.Approvisionnement', models.DO_NOTHING, db_column='id_appro')
    id_produit = models.ForeignKey('Produit', models.DO_NOTHING, db_column='id_produit')
    quantite = models.IntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=0)

    class Meta:
        managed = True
        db_table = 'ligne_appro'


class LigneCommande(models.Model):
    id_lignecmd = models.AutoField(db_column='id_ligneCmd', primary_key=True)  # Field name made lowercase.
    id_commande = models.ForeignKey('baseSQL.Commande', models.DO_NOTHING, db_column='id_commande')
    id_produit = models.ForeignKey('Produit', models.DO_NOTHING, db_column='id_produit')
    quantite = models.IntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)
    montant_total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = True
        db_table = 'ligne_commande'


class LigneVente(models.Model):
    id_ligne = models.AutoField(primary_key=True)
    id_vente = models.ForeignKey('baseSQL.Vente', models.DO_NOTHING, db_column='id_vente')
    id_produit = models.ForeignKey('baseSQL.Produit', models.DO_NOTHING, db_column='id_produit')
    quantite = models.IntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)
    sous_total = models.DecimalField(max_digits=10, decimal_places=2)
    quantite_retournee = models.PositiveIntegerField(default=0)

    class Meta:
        managed = True
        db_table = 'ligne_vente'





class Stock(models.Model):
    id_stock = models.AutoField(primary_key=True)
    id_produit = models.ForeignKey('baseSQL.Produit', models.DO_NOTHING, db_column='id_produit')
    sueil_alerte = models.IntegerField()
    quantite = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = True
        db_table = 'stock'
        
class RetourProduit(models.Model):

accounts/forms.py
from django import forms
from baseSQL.models import Utilisateur
class LoginForm(forms.Form):
    user = forms.CharField(label="username")
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

class CaissierCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Mot de passe")


    class Meta:
        model = Utilisateur
        fields = ['username', 'email', 'contact','adresse', 'password']

def save(self, commit= True):
    user = super().save(commit=False)
    user.set_password(self.cleaned_data['password'])### hash du mot de passe
    user.role= 'caissier'
    user.is_active = True  # Activation de l'utilisateur
    if commit:
        user.save()
    return user            



#####Formulairede modifciation caissier

class CaissierForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['username', 'contact','first_name', 'last_name','email',  'adresse']


### Modificationdes informations users
# from django import forms
from baseSQL.models import Utilisateur

class ProfilForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['first_name', 'last_name', 'email', 'contact', 'adresse', 'photo']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
            'adresse': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
        }

class PhotoProfilForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['photo']  #         


class InfosProfilForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['first_name','last_name', 'email', 'contact', 'adresse']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
            'adresse': forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/templates/ajouter_caissier.html
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Création Caissier</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <!-- Bootstrap Icons CDN -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">

  <style>
    body {
      background-color: #f5f5f5;
      color: #f5f5f5;
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 40px;
    }.btn-retour {
  position: fixed;
  top: 20px;
  left: 20px;
  background-color: #000000e5;
  color: #fff;
  border: 2px solid #e60000;
  border-radius: 50%;
  padding: 12px 14px;
  font-size: 20px;
  z-index: 1000;
  transition: all 0.3s ease;
}

.btn-retour:hover {
  background-color: #e60000;
  color: #fff;
  transform: scale(1.1);
}


    h2 {
      color: #e60000;
      text-align: center;
      margin-bottom: 30px;
    }

    .form-container {
      background-color: #1e1e1e;
      padding: 30px;
      border-radius: 12px;
      box-shadow: 0 4px 12px rgba(230, 0, 0, 0.2);
      max-width: 500px;
      margin: auto;
    }

    .form-container p {
      display: flex;
      flex-direction: column;
      margin-bottom: 20px;
    }

    .form-container label {
      font-weight: 600;
      margin-bottom: 5px;
    }

    .form-container input {
      padding: 10px;
      border-radius: 8px;
      border: none;
      background-color: #2a2a2a;
      color: #f1f1f1;
    }

    .form-container input:focus {
      outline: none;
      border: 1px solid #e60000;
      box-shadow: 0 0 6px rgba(230, 0, 0, 0.5);
    }

    .form-container button {
      background-color: #e60000;
      border: none;
      padding: 12px;
      width: 100%;
      color: white;
      font-weight: bold;
      font-size: 1rem;
      border-radius: 8px;
      transition: background 0.3s ease;
      margin-top: 10px;
    }

    .form-container button:hover {
      background-color: #c20000;
    }

    .message {
      list-style: none;
      padding: 0;
      max-width: 500px;
      margin: 0 auto 20px auto;
    }

    .error {
      background-color: #2a0000;
      border-left: 4px solid #e60000;
      padding: 10px;
      margin-bottom: 10px;
      color: #ffcccc;
    }

    .form-container i {
      margin-right: 8px;
      color: #e60000;
    }
  </style>
</head>
<body>
    <!-- Bouton Retour en haut à gauche -->
<a href="{% url 'gestion_caissier' %}" class="btn btn-retour">
  <i class="bi bi-arrow-left-circle-fill"></i>
</a>

  <h2><i class="fas fa-user-plus"></i> Création d’un Caissier</h2>

  {% if messages %}
  <ul class="message">
      {% for message in messages %}
      <li class="error"><i class="fas fa-exclamation-circle"></i> {{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <form method="post" class="form-container">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"><i class="fas fa-save"></i> Créer le caissier</button>
  </form>

</body>
</html>

accounts/templates/caissier_change_password.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Changement de mot de passe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS (si besoin) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Ton CSS personnalisé -->
    
    <style>
        /* Styles spécifiques pour cette page */
        body {
            background-color: #f5f5f5;
            color: #ffffff;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
        }

        .container {
            background-color: #1a1a1a;
            border: 2px solid #ff0000;
            border-radius: 15px;
            padding: 40px;
            max-width: 500px;
            width: 100%;
            box-shadow: 0 0 20px rgba(255, 0, 0, 0.3);
            animation: fadeIn 0.6s ease-in-out;
        }

        h2 {
            text-align: center;
            color: #ff0000;
            margin-bottom: 25px;
        }

        form p {
            margin-bottom: 20px;
        }

        form input[type="password"] {
            background-color: #2a2a2a;
            border: 1px solid #ff0000;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            width: 100%;
        }

        .btn {
            background-color: #ff0000;
            color: #fff;
            border: none;
            width: 100%;
            padding: 10px;
            font-weight: bold;
            border-radius: 8px;
            transition: background-color 0.3s ease;
        }

        .btn:hover {
            background-color: #cc0000;
        }

        ul.message {
            list-style: none;
            padding: 0;
            margin-bottom: 20px;
        }

        .message .error {
            background-color: #660000;
            padding: 10px;
            border-radius: 5px;
            color: #ffaaaa;
            border: 1px solid #ff0000;
            margin-bottom: 10px;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
    </style>
</head>
<body>

<div class="container">
    <h2>Veuillez changer votre mot de passe</h2>

    {% if messages %}
    <ul class="message">
        {% for message in messages %}
        <li class="error">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Changer le mot de passe</button>
    </form>
</div>

</body>
</html>

accounts/templates/dashboard_caissier.html
{% extends "core/templates/nav.html" %}

{% load static%}

{% block extra_css%}
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'dashboard_caissier.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
{% endblock%}
{% block content %}

   <div class="container py-4">
    <h2 class="mb-4">Bienvenue, Caissier</h2>

    <!-- Actions principales -->
    <div class="row g-4">
        <div class="col-md-4">
            <a href="{% url 'vente' %}" style="text-decoration: none;">
            <div class="card card-action text-center p-3">
                <i class="fas fa-cash-register mb-2"></i>
                <h5>Nouvelle Vente</h5>
            </div>
            </a>
        </div>
        <div class="col-md-4">
           <a href="{% url 'liste_ventes' %}" style="text-decoration: none;">
             <div class="card card-action text-center p-3">
                <i class="fas fa-receipt mb-2"></i>
                <h5> Mes ventes</h5>

            </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'liste_ventes' %}" style="text-decoration: none;">
            <div class="card card-action text-center p-3">
                <i class="fas fa-user-plus"></i>
                <h5>Ajouter client</h5>
            </div>
            </a>
        </div>
       
    </div>

    <!-- Statistiques personnelles -->
    <div class="row mt-5">
        <div class="col-md-5">
            <div class="chart-card p-3">
                <h6 class="text-white">Total des ventes de la semaine</h6>
                <div id="salesChart"></div>
            </div>
        </div>
        <div class="col-md-6 mt-4">
            <div class="stat-card">
                <h6>Clients ajoutés aujourd'hui</h6>
                <h3 class="text-danger">4</h3>
            </div>
        </div>
    </div>
</div>

<script>
    var options = {
        chart: {
            type: 'line',
            height: 250,
            toolbar: { show: false },
            background: '#1a1a1a'
        },
        series: [{
            name: "Ventes",
            data: [4000, 7000, 8000, 12000, 9000, 15000, 18000]
        }],
        xaxis: {
            categories: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim']
        },
        colors: ['#e60000'],
        dataLabels: {
            enabled: false
        },
        stroke: {
            curve: 'smooth'
        }
    };
    var chart = new ApexCharts(document.querySelector("#salesChart"), options);
    chart.render();
</script>
{% endblock %}

accounts/templates/liste_ventes.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
        <!-- Bootstrap 5 CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap JS Bundle (inclut Popper) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

    </head>
    <body>
    <div class="container-fluid mt-4 px-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h4 class="text-dark">
      <i class="fas fa-receipt text-danger me-2"></i> Toutes les Ventes
    </h4>
  </div>

  <!-- Filtres de date -->
  <div class="card shadow-sm rounded p-3 mb-4 bg-white border-0">
    <form method="get" class="row g-3">
      <div class="col-md-3">
        <input type="date" name="date_debut" value="{{ date_debut }}" class="form-control border-dark rounded" placeholder="Date début">
      </div>
      <div class="col-md-3">
        <input type="date" name="date_fin" value="{{ date_fin }}" class="form-control border-dark rounded" placeholder="Date fin">
      </div>
      <div class="col-md-2">
        <button type="submit" class="btn btn-danger w-100 rounded">Filtrer</button>
      </div>
    </form>
  </div>

  <div class="card shadow-sm rounded bg-white p-3">
    <table class="table table-hover align-middle">
      <thead class="table-dark text-center">
        <tr>
          <th>Date</th>
          <th>Code Facture</th>
          <th>Client</th>
          <th>Total</th>
          <th>Auteur</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for vente in ventes %}
          {% with facture=vente.facture_set.first %}
          <tr class="text-center align-middle">
            <td>{{ vente.date_vente|date:"d M Y H:i" }}</td>
            <td class="fw-semibold text-dark">{{ facture.code_facture }}</td>
            <td>{{ vente.id_client.nom_client }}</td>
            <td class="text-danger fw-bold">{{ vente.montanttotal }} FCFA</td>
            <td class="d-flex align-items-center justify-content-start">
              {% if vente.id_utilisateur.photo %}
              <img src="{{ vente.id_utilisateur.photo.url }}" alt="photo" class="rounded-circle me-2" width="32" height="32">
              {% else %}
                <img src="{% static 'img/default-avatar.png' %}" alt="photo" class="rounded-circle me-2" width="32" height="32">
               {% endif %}
              {{ vente.id_utilisateur.get_full_name }}
            </td>
            <td>
             

              {% if facture %}
              <a href="{% url 'imprimer_facture' facture.code_facture %}" class="btn btn-sm btn-outline-danger" target="_blank" title="Imprimer">
                <i class="fas fa-print"></i>
              </a>
              {% endif %}
            </td>
          </tr>
          {% endwith %}
        {% empty %}
          <tr>
            <td colspan="6" class="text-center text-muted">Aucune vente trouvée.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</html>

accounts/templates/modifier_profil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container mt-5">
    <h2>Modifier mon profil</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Enregistrer</button>
    </form>
</div>
</body>
</html>