Gestcom_coccinelle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('produits/', include('Produits.urls')),
    path('stock/', include('Stocks.urls')),
    path('vente/', include('Vente.urls')),
    path('tiers/', include('tiers.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Produits/urls.py
from django.urls import path
from . import views

urlpatterns  = [
    path('', views.liste_produits, name='produits'),
    path('ajouter/', views.ajouter_produit, name='ajouter_produit'),
    path('produits/modifier/<int:pk>/', views.modifier_produit, name='modifier_produit'),
    path('produits/supprimer/<int:pk>/', views.supprimer_produit, name='supprimer_produit'),

    path('liste/produit/', views.all_produit, name='all_produit'),

    path('scan/produit/', views.scan_produit, name='scan_produit'),


    path('produits/modifier/<int:pk>/', views.edit_product, name='edit_product'),
    path('produits/supprimer/<int:pk>/', views.delete_product, name='delete_product'),
    # urls.py du projet

]

core/urls.py
from django.urls import path
from .views import home 


urlpatterns = [
    path('', home, name='home'),
    
]

Produits/models.py
from django.db import models

# Create your models here.

baseSQL/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from datetime import date
from django.utils import timezone
from datetime import timedelta


class Utilisateur(AbstractUser):

    ROLE_CHOICES= [
        ('admin', 'Administrateur'),
        ('caissier','Caissier'),
    ]
    last_activity = models.DateTimeField(null=True, blank=True)
    id_utilisateur = models.AutoField(primary_key=True)
    contact = models.CharField(max_length=250, unique=True)
    adresse = models.CharField(max_length=100)
    email =models.CharField(max_length=100, unique=True)
    role = models.CharField(max_length=8, choices=ROLE_CHOICES, default='caissier')
    statut = models.CharField(max_length=7)
    photo = models.ImageField(upload_to='accounts/', null=True, blank=True)
    ##fist_login= models.BooleanField(default=True)


    def __str__(self):
        return self.username
    @property
    def is_online(self):
        if self.last_activity:
            return timezone.now() - self.last_activity < timedelta(seconds=30)
        return False
    
    class Meta:
        managed = True
        db_table = 'utilisateur'

class ProfilCaissier(models.Model):
    utilisateur = models.OneToOneField('baseSQL.Utilisateur', on_delete=models.CASCADE)
    first_login= models.BooleanField(default=True)

    class Meta:
        managed = True
        db_table = 'profil_caissier'
class Approvisionnement(models.Model):
    id_appro = models.AutoField(primary_key=True)
    id_utilisateur = models.ForeignKey('baseSQL.Utilisateur', models.DO_NOTHING, db_column='id_utilisateur')
    id_frs = models.ForeignKey('Fournisseur', models.DO_NOTHING, db_column='id_frs')
    date = models.DateTimeField()
    montant_total = models.DecimalField(max_digits=10, decimal_places=2)
    date_expiration = models.DateField(null=True, blank=True)  

    def est_proche_expiration(self):
        if self.date_expiration:
            delta = (self.date_expiration - date.today()).days
            return 0 < delta <= 7
        return False

    def est_expire(self):
        if self.date_expiration:
            return self.date_expiration < date.today()
        return False

    class Meta:
        managed = True
        db_table = 'approvisionnement'


class MouvementStock(models.Model):
    TYPE_CHOICES = [
        ('entrée', 'Entrée'),
        ('sortie','Sortie'),
        ('retour', 'Retour'),
        ('ajustement', 'Ajustement'),
        ('aprovisionement','Approvisionement'),
        ('transfert','Transfert'),
    ]

    produit = models.ForeignKey('baseSQL.Produit', on_delete=models.CASCADE)
    type_mouvement = models.CharField(max_length=20, choices=TYPE_CHOICES)
    quantite = models.IntegerField()
    utilisateur  =  models.ForeignKey('baseSQL.Utilisateur', on_delete=models.SET_NULL, null=True)
    date_mouvement = models.DateTimeField(auto_now_add=True)
    commentaire= models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.type_mouvement} - {self.produit.nom} ({self.quantite})"
    class Meta:
        managed = True
        db_table = 'mouvement_stock'        

class Vente(models.Model):
    id_vente = models.AutoField(primary_key=True)
    id_client = models.ForeignKey('baseSQL.Client', models.DO_NOTHING, db_column='id_client')
    id_utilisateur = models.ForeignKey('baseSQL.Utilisateur', models.DO_NOTHING, db_column='id_utilisateur', related_name='ventes')
    date_vente = models.DateTimeField()
    montanttotal = models.DecimalField(db_column='montantTotal', max_digits=10, decimal_places=2)  # Field name made lowercase.
    remise = models.DecimalField(max_digits=5, decimal_places=2, default=0, verbose_name="Remise (%)")

    statut = models.CharField(max_length=10)

    class Meta:
        managed = True
        db_table = 'vente'


class Commande(models.Model):
    id_commande = models.AutoField(primary_key=True)
    id_client= models.ForeignKey('baseSQL.Client', models.DO_NOTHING, db_column='id_client')
    id_utilisateur = models.ForeignKey('baseSQL.Utilisateur', models.DO_NOTHING, db_column='id_utilisateur')
    id_frs= models.ForeignKey('baseSQL.Fournisseur', models.DO_NOTHING, db_column='id_frs')

    date_commande = models.DateTimeField()
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = True
        db_table = 'commande'        


class CategorieProduit(models.Model):
    id_categorie = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=100)
    description = models.TextField()
    def __str__(self):
        return self.nom
    class Meta:
        managed = True
        db_table = 'categorie_produit'

class Produit(models.Model):
    id_produit = models.AutoField(primary_key=True)
    categorie = models.ForeignKey('baseSQL.CategorieProduit', on_delete=models.CASCADE)
    nom_produit = models.CharField(max_length=100)
    codes_barres = models.CharField(max_length=100, unique=True, null=True, blank=True)
    reference = models.CharField(max_length=100)
    description = models.TextField()
    quantite = models.IntegerField()
    prix_achat = models.DecimalField(max_digits=10, decimal_places=2)
    prix_vente = models.DecimalField(max_digits=10, decimal_places=2)
    stock_actuel = models.IntegerField()
    stock_min = models.IntegerField()
    image = models.ImageField(upload_to='produits/', blank=True, null=True)
    def __str__(self):
        return f"{self.nom_produit} ({self.reference})"
    class Meta:
        managed = True
        db_table = 'produit'        



class Client(models.Model):
    id_client = models.AutoField(primary_key=True)
    nom_client = models.CharField(max_length=100)
    contact = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=255, unique=True,blank=True, null=True)
    adresse = models.CharField(max_length=255, blank=True, null=True)
    point = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.nom_client} - {self.contact}"
    
    class Meta:
        managed = True
        db_table = 'client'




class Facture(models.Model):
    id_facture = models.AutoField(primary_key=True)
    id_vente = models.ForeignKey('Vente', models.DO_NOTHING, db_column='id_vente')
    code_facture = models.CharField(max_length=100)
    date_emission = models.DateTimeField()
    date_paiement = models.DateTimeField()
    montant_ht = models.DecimalField(db_column='montant_HT', max_digits=10, decimal_places=2)  # Field name made lowercase.
    montant_ttc = models.DecimalField(db_column='montant_TTC', max_digits=10, decimal_places=2)  # Field name made lowercase.
    montant_net = models.DecimalField(max_digits=10, decimal_places=2)
    mode_paiement = models.CharField(max_length=11)

    class Meta:
        managed = True
        db_table = 'facture'


class Fournisseur(models.Model):
    id_frs = models.AutoField(primary_key=True)
    nom_frs = models.CharField(max_length=100)
    contact = models.CharField(max_length=100, unique=True)
    email = models.CharField(max_length=100, unique=True)
    adresse = models.CharField(max_length=100)
    pays = models.CharField(max_length=100)
    type_frs = models.CharField(max_length=11)

    def __str__(self):
        return f"{self.nom_frs}"
    class Meta:
        managed = True
        db_table = 'fournisseur'


class LigneAppro(models.Model):
    id_ligneappro = models.AutoField(db_column='id_ligneAppro', primary_key=True)  # Field name made lowercase.
    id_appro = models.ForeignKey('baseSQL.Approvisionnement', models.DO_NOTHING, db_column='id_appro')
    id_produit = models.ForeignKey('Produit', models.DO_NOTHING, db_column='id_produit')
    quantite = models.IntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=0)

    class Meta:
        managed = True
        db_table = 'ligne_appro'


class LigneCommande(models.Model):
    id_lignecmd = models.AutoField(db_column='id_ligneCmd', primary_key=True)  # Field name made lowercase.
    id_commande = models.ForeignKey('baseSQL.Commande', models.DO_NOTHING, db_column='id_commande')
    id_produit = models.ForeignKey('Produit', models.DO_NOTHING, db_column='id_produit')
    quantite = models.IntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)
    montant_total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = True
        db_table = 'ligne_commande'


class LigneVente(models.Model):
    id_ligne = models.AutoField(primary_key=True)
    id_vente = models.ForeignKey('baseSQL.Vente', models.DO_NOTHING, db_column='id_vente')
    id_produit = models.ForeignKey('baseSQL.Produit', models.DO_NOTHING, db_column='id_produit')
    quantite = models.IntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)
    sous_total = models.DecimalField(max_digits=10, decimal_places=2)
    quantite_retournee = models.PositiveIntegerField(default=0)

    class Meta:
        managed = True
        db_table = 'ligne_vente'





class Stock(models.Model):
    id_stock = models.AutoField(primary_key=True)
    id_produit = models.ForeignKey('baseSQL.Produit', models.DO_NOTHING, db_column='id_produit')
    sueil_alerte = models.IntegerField()
    quantite = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = True
        db_table = 'stock'
        
class RetourProduit(models.Model):

Produits/forms.py
from django import forms
from baseSQL.models import Produit, CategorieProduit

#FORMULAIRED'AJOUT DEPRODUIT
class ProduitForm (forms.ModelForm):
    categorie = forms.ModelChoiceField(
        queryset=CategorieProduit.objects.all(),
        empty_label="selectionnez une categorie",
        widget=forms.Select(attrs={'class':'form-control'})
     )
    
    codes_barres = forms.CharField(
        required=False,
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Scannez le codes-barres'
        })
    )
    class Meta:
        model = Produit
        fields = ['nom_produit', 'reference',  'description', 'quantite', 
                  'prix_achat', 'prix_vente', 'stock_actuel','stock_min', 'categorie', 'image', 'codes_barres']
       
        
        widgets = {
            'nom_produit' : forms.TextInput(attrs={'class': 'from-control'}),
            
            'reference' : forms.TextInput(attrs={'class': 'from-control', 'rows':2}),
            'description': forms.Textarea(attrs={'class': 'from-control', 'rows':2}),
            'quantite': forms.NumberInput(attrs={'class': 'from-control'}),
            'prix_achat': forms.NumberInput(attrs={'class': 'from-control'}),
            'prix_vente' : forms.NumberInput(attrs={'class': 'from-control'}),
            'stock_actuel':  forms.NumberInput(attrs={'class': 'from-control'}),
            'stock_min': forms.NumberInput(attrs={'class': 'from-control'}),
            ##'image': forms.ImageField(),
            'image': forms.FileInput()

        }

    def clean_codes_barres(self):
        codes_barres = self.cleaned_data.get('codes_barres')
        if codes_barres:
            # Exclure l'instance en cours (modification)
            qs = Produit.objects.filter(codes_barres=codes_barres)
            if self.instance.pk:
                 qs = qs.exclude(pk=self.instance.pk)

            if qs.exists():
                raise forms.ValidationError("Ce code-barres est déjà utilisé par un autre produit.")
        return codes_barres

Stocks/forms.py
from django import forms
from baseSQL.models import Produit, Fournisseur , CategorieProduit


class ApprovisionnementForm(forms.Form):
    produit = forms.ModelChoiceField(
        queryset = Produit.objects.all(),
        widget=forms.Select(attrs={'class': 'select-input'}),
        label='Produit'
    )

    fournisseur = forms.ModelChoiceField(
        queryset=Fournisseur.objects.all(),
        widget=forms.Select(attrs={'class': 'select-input'}),
        label='Fournisseur'
    )

    quantite = forms.IntegerField(
        min_value=1,
        widget=forms.NumberInput(attrs={'class':'text-input'}),
        label= 'Quantité'
    )

    prix = forms.DecimalField(
        max_digits=10,
        decimal_places=2,

        widget=forms.NumberInput(attrs={'class':'text-input'}),
        label= 'Prix Unitaire'
    )
    date_expiration = forms.DateField(
    label="Date d’expiration (optionnel)",
    required=False,
    widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control'
        })
    )

class ApprovisionnementForm0(forms.Form):
    codes_barres = forms.CharField(
        label="Scanner le code-barres", 
        required=False, 
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Scannez un code-barres...',
            'id': 'barcodeInput'
        })
    )

    quantite = forms.IntegerField(
        label="Quantité à ajouter",
        min_value=1,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': 'Quantité'
        })
    )

    prix_achat = forms.DecimalField(
        label="Prix d’achat unitaire",
        max_digits=10, decimal_places=2,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': 'Prix d’achat'
        })
    )

    prix_vente = forms.DecimalField(
        label="Prix de vente unitaire",
        max_digits=10, decimal_places=2,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': 'Prix de vente'
        })

    )

    fournisseur = forms.ModelChoiceField(
        label="Fournisseur",
        queryset=Fournisseur.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    date_expiration = forms.DateField(
        label="Date d’expiration (optionnel)",
        required=False,
        widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control'
        })
    )


    # CATEGORIE DE PRODUITS

class CategorieForm(forms.ModelForm):
    class Meta:
        model = CategorieProduit
        fields = ['nom', 'description']  # adapte selon ton modèle
        widgets = {
            'nom': forms.TextInput(attrs={'class': 'form-control', }),
            'description': forms.Textarea(attrs={'class': 'form-control','rows':'1'})
        }

Vente/forms.py
from django import forms
from baseSQL.models import Vente, LigneVente, Produit

class ClientForm(forms.Form):
    produit = forms.ModelChoiceField(queryset=Produit.objects.all(), label="Produit")
    quantite = forms.IntegerField(min_value=1, label="Quantité")
    prix_unitaire = forms.FloatField(min_value=0.0, label="Prix unitaire")

    def clean(self):
        cleaned_data = super().clean()
        produit = cleaned_data.get("produit")
        quantite = cleaned_data.get("quantite")

        if produit and quantite:
            if quantite > produit.quantite:
                raise forms.ValidationError(
                    f"La quantité demandée ({quantite}) dépasse le stock disponible ({produit.stock_actuel}) pour {produit.nom_produit}."
                )
        return cleaned_data


class VenteForm(forms.ModelForm):
    class Meta:
        model = Vente
        fields = ['id_client']

Produits/templates/ajouter_produit.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire Produits</title>
    <!-- Bootstrap 5 CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap JS Bundle (inclut Popper) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="{% static 'ajouter_produit.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>
<body>

    
  <!-- Bouton Retour -->
  <button id="btn-retour" class=" btn btn-outline-danger btn-back">
    <i class="fas fa-arrow-left"></i> 
  </button>
  <script>
     document.getElementById("btn-retour").addEventListener("click", () => {
    window.history.back();
  });
  </script>
   
    <div class="form-container">
    <div class="form-box">
        <h2><i class="fas fa-box"></i>  Ajout de nouvel Produit</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group">
                    <label for="id_nom_produit"><i class="fas fa-tag"></i> Nom</label>
                    {{ form.nom_produit }}
                </div>
                <div class="form-group">
                    <label for="id_quantite"><i class="fas fa-sort-numeric-up"></i> Quantité</label>
                    {{ form.quantite }}
                </div>
                <div class="form-group">
                    <label for="id_codes_barres"><i class="fas fa-barcode"></i> Code-Barre</label>
                    {{ form.codes_barres }}
                </div>
                 <div class="form-group">
                    <label for="id_reference"><i class="fas fa-align-left"></i> Référence</label>
                    {{ form.reference }}
                </div>
               
            </div>




             <div class="form-group">
                    <label for="id_categorie"><i class="fas fa-list"></i> Catégorie</label>
                    {{ form.categorie }}
                </div>
            

           

            <div class="form-row">

               
                <div class="form-group">
                    <label for="id_prix_achat"><i class="fas fa-money-bill"></i> Prix d'achat</label>
                    {{ form.prix_achat }}
                </div>
                <div class="form-group">
                    <label for="id_prix_vente"><i class="fas fa-money-check"></i> Prix de vente</label>
                    {{ form.prix_vente }}
                </div>
                 <div class="form-group">
                    <label for="id_image"><i class="fas fa-image"></i> Image</label>
                    {{ form.image }}
                </div>
                <div class="form-group">
                    <label for="id_stock_actuel"><i class="fas fa-boxes"></i> Stock actuel</label>
                    {{ form.stock_actuel }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                <label for="id_description"><i class="fas fa-align-left"></i> Description</label>
                {{ form.description }}
               </div>

               <div class="form-group">
                <label for="id_stock_min"><i class="fas fa-exclamation-triangle"></i> Seuil minimum</label>
                {{ form.stock_min }}
            </div>
            </div>

            
            

            <div class="button-group">
                <button type="submit" class="btn btn-success">
                    <i class="fas fa-save"></i> Enregistrer
                </button>
                <a href="{% url 'produits' %}" class="btn btn-secondary">
                    <i class="fas fa-times-circle"></i> Annuler
                </a>
                
            </div>

            {% if messages %}
            <ul class="message">
                {% for message in messages %}
                    <li class="error">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </form>
    </div>
</div>


  
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const btnRetour = document.getElementById('btn-retour');
    if (btnRetour) {
      btnRetour.addEventListener('click', function () {
        window.history.length > 1 ? window.history.back() : window.location.href = '/';  // Redirige vers la page d’accueil si pas de précédent
      });
    }
  });
</script>


 {% if messages %}
  <div id="custom-alert-wrapper" class="d-flex justify-content-center align-items-center position-fixed top-0 start-0 w-100 h-100" style="z-index: 1055;">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center shadow-lg rounded-3" style="background-color: rgb(235, 234, 234); min-width: 350px; max-width: 500px; padding: 20px;">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close position-absolute top-0 end-0 m-2" data-bs-dismiss="alert" aria-label="Fermer"></button>
      </div>
    {% endfor %}
  </div>

  <script>
    // Disparition automatique après 5s
    setTimeout(function () {
      const alertWrapper = document.getElementById('custom-alert-wrapper');
      if (alertWrapper) {
        alertWrapper.style.opacity = '0';
        alertWrapper.style.transition = 'opacity 0.5s ease';
        setTimeout(() => {
          alertWrapper.remove();
        }, 500);
      }
    }, 5000);
  </script>
{% endif %}
</body>
</html>